### test
POST http://localhost:3000/api/contact/test

### test verify jwt
GET http://localhost:3000/api/jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjIyMiIsImlhdCI6MTcyOTgzOTQyMywiZXhwIjoxNzI5ODQzMDIzfQ.FpoeIllEFMRatG-Ka1nR1rRL1egA2SY-NMjyJlbFOic

### login
POST  http://localhost:3000/api/user/login  HTTP/1.1
Content-Type:  application/json

{
    "username":"fucker001",
    "password":"88888888"
}

### user register
POST  http://localhost:3000/api/user/register  HTTP/1.1
Content-Type:  application/json

{
    "username":"arthas002",
    "password":"00000000",
    "repeat":"00000000"
    
}

###
GET http://localhost:3000/api/user/jwt  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZ1Y2tlcjAwMSIsImlhdCI6MTczMDYxNjgxMywiZXhwIjoxNzMwNjIwNDEzfQ.Vzonew9mJmTkxkDoBuEEo7dFzsxaT0J-OrUTtXrGbc8

### contact create
POST http://localhost:3000/api/contact/create  HTTP/1.1
Content-Type:  application/json

{
    "username":"fucker003"
}

###  insert friend into user's friend list
POST http://localhost:3000/api/contact/add  HTTP/1.1
Content-Type:  application/json

{
    "username":"fucker001",
    "friend_name":"fucker004",
    "friend_displayName":"qbac",
    "friend_img_url":"https://www.nylabone.com/-/media/project/oneweb/nylabone/images/dog101/activities-fun/10-great-small-dog-breeds/maltese-portrait.jpg"
}

### get user's friend list
GET http://localhost:3000/api/contact/get/fucker001  HTTP/1.1
Content-Type: application/json

### remove a friend from the friend list
POST http://localhost:3000/api/contact/remove
Content-Type:  application/json

{
    "username":"fucker001",
    "friend_name":"fucker003"
}

### search user
GET http://localhost:3000/api/user/search/fucker001  HTTP/1.1
Content-Type: application/json

### check the relationship
GET http://localhost:3000/api/contact/is/fucker001/fucker002  HTTP/1.1
Content-Type: application/json